application:
  server:
    port: 8080
spring:
  main:
    allow-circular-references: true
  application:
    name: HadBotchichik
bot:
  token: 1462914779:AAEuZZCpRlkaMvme_D3owMEhQgAElU6d0gE
  name: BotBottoBot
